using FFImageLoading.Forms;
using Plugin.Media.Abstractions;
using StorageDex_Mobile.elements;
using StorageDex_Mobile.lib;
using StorageDex_Mobile.lib.interfaces;
using StorageDex_Mobile.lib.interfaces.toolbar;
using StorageDex_Mobile.pages.miscPages;
using StorageDexLib;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace StorageDex_Mobile.pages.newPages
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class NewItemPage : ContentPage, INewPage, IRefreshable, IConfirmable, IToolbarDelete
    {

        /**
        * a page to create a new container
        */

        public MediaFile finalImage;
        private int newItemId; //the id of the item- generated by the database
        private Item previousItem;
        private bool isEditing = false; //if the page is being used to edit an item
        private TagDisplay tagDisplay;
        private StorageContainer container;

        public NewItemPage(StorageContainer container)
        {
            this.container = container;
            InitializeComponent();
            newItemId = DatabaseHandler.GetDatabase().GenerateNewItemId(); //get the id for the new container

            //set colors
            this.BackgroundColor = PageColors.secondaryColor;

            InitContent();

            tagDisplay = new TagDisplay();
            this.tagDisplayWrapper.Children.Add(tagDisplay);
        }


        //for editing a preexisting item
        public NewItemPage(string name, string notes, List<string> tags, int id, Item prevItem, StorageContainer container) : base()
        {
            this.container = container;
            InitializeComponent();
            InitContent();
            newItemId = id;
            this.nameInput.Text = name;
            this.notesEditor.Text = notes;
            this.codeInput.Text = prevItem.barcode;

            this.previousItem = prevItem;
            this.isEditing = true;

            if (isEditing)
            {
                this.Title = "Editing";
            }


            //set colors
            this.BackgroundColor = PageColors.secondaryColor;

            InitContent();

            tagDisplay = new TagDisplay();
            this.tagDisplayWrapper.Children.Add(tagDisplay);
            tagDisplay.AddTagBatch(tags);

            //set image
            if (ImageTools.HasImage(previousItem))
            {

                if (ImageBaseHandler.current.isItemCached(previousItem.GetId()))
                {
                    SetImageHolderContent(ImageBaseHandler.current.GetItemImageSource(previousItem.GetId()));
                }
                else
                {
                    ImageSource imageLoadTask = ImageTools.LoadImage(System.IO.Path.Combine(Directories.itemImageDirectory, id.ToString() + ".jpg"));
                    SetImageHolderContent(imageLoadTask);
                }



            }


        }

        //initializes the content on the page 
        private void InitContent()
        {

            this.itemName.TextColor = PageColors.textColor;
            this.nameInput.TextColor = PageColors.textColor;
            this.tags.TextColor = PageColors.textColor;
            this.tagsInput.TextColor = PageColors.textColor;
            this.notes.TextColor = PageColors.textColor;
            this.notesEditor.TextColor = PageColors.textColor;
            this.itemAmount.TextColor = PageColors.textColor;
            this.amountInput.TextColor = PageColors.textColor;
            this.itemCode.TextColor = PageColors.textColor;
            this.codeInput.TextColor = PageColors.textColor;

            this.imageHolder.WidthRequest = MasterNavigationPage.current.Width - 5;

            this.addCodeButton.BackgroundColor = Color.Transparent;

            if (isEditing)
            {
                amountInput.Text = previousItem.GetAmount().ToString();
            }
            else
            {
                amountInput.Text = "1";
            }

            


        }


        //handles the tag input box
        //moves the new tag onto the line below when it is finished
        private void TagInputOnType(Object sender, TextChangedEventArgs args)
        {
            string text = tagsInput.Text;
            if (text.Trim() == ",")
            {
                tagsInput.Text = "";
            }
            else if (text.EndsWith(",")) //if ends with comma, tag is finished
            {
                string newTag = text.Substring(0, text.Length - 1);
                TagButton newTagButton = new TagButton(newTag);
                tagDisplay.AddTag(newTagButton);
                tagsInput.Text = "";

            }
        }

        //handles the enter key being pressed on tag input 
        private void TagInputCompleted(Object sender, EventArgs args)
        {
            string text = tagsInput.Text;
            if (text.Trim() == "," || text.Trim() == "")
            {
                tagsInput.Text = "";
            }
            else
            {
                tagsInput.Text = "";
                TagButton newTagButton = new TagButton(text);
                tagDisplay.AddTag(newTagButton);

            }
        }

        //sets the image holder content
        private void SetImageHolderContent(ImageSource imageIn)
        {
            ImageButton newButton = new ImageButton() { Source = imageIn };
            this.imageHolder.Content = newButton;
            newButton.Clicked += (sen, e) => Navigation.PushAsync(new ImagePage(imageIn));
        }

        //asks the user to pic a photo
        public async void AttachPhoto()
        {
            if (await UserPermissions.ValidateStoragePermissions()) //check permissions
            {
                MediaFile picked = await ExternalResources.PickPhoto();
                FinalizePhoto(picked);

            }
        }

        //has the user take a photo
        public async void TakePhoto()
        {
            if (await UserPermissions.ValidateStoragePermissions() && await UserPermissions.ValidateCameraPermissions()) //check permissions
            {

                MediaFile taken = await ExternalResources.TakePhoto();
                FinalizePhoto(taken);
            }
        }


        //finalizes a selected photo. puts it in the right directory and display it on the page
        private void FinalizePhoto(MediaFile imageIn)
        {
            CachedImage loadingImage = new CachedImage()
            {
                Source = "loading"
            };

            if (imageIn != null)
            {
                this.imageHolder.Content = loadingImage;
                finalImage = imageIn;
                SetImageHolderContent(ImageTools.MediaFileToImageSource(imageIn));

            }



        }


        //refreshes the current page
        public void Refresh()
        {

            RefreshTags();
            if (finalImage == null)
            {
                this.imageHolder.Content = null;
            }
            else
            {
                SetImageHolderContent(ImageTools.MediaFileToImageSource(finalImage));
            }


        }

        //refreshes the current tags on the page
        private void RefreshTags()
        {
            tagDisplay.RefreshTags();
        }


        //confirms the new item
        public async void Confirm()
        {

            CreateItem();
            if (finalImage != null)
            {
                await ImportPhoto(finalImage);
            }
            Finish();
        }

        //creates the item and adds to database
        private void CreateItem()
        {

            List<string> tagNamesList = new List<string>();
            foreach (TagButton button in tagDisplay.GetTags())
            {
                if (!tagNamesList.Contains(button.GetButtonText()))
                {

                    tagNamesList.Add(button.GetButtonText());
                }

            }
            if (isEditing) //if editing a previous container, change the value
            {
                previousItem.name = nameInput.Text.Trim();
                previousItem.tags = tagNamesList;
                previousItem.notes = notesEditor.Text;
                previousItem.barcode = codeInput.Text;
                previousItem.SetAmount(Int32.Parse(amountInput.Text));

            }
            else
            {


                Item newItem = new Item(newItemId, container, nameInput.Text.Trim(), tagNamesList, notesEditor.Text, Int32.Parse(amountInput.Text), codeInput.Text);
                Console.WriteLine("tags");
                foreach (string tag in tagNamesList)
                {
                    Console.WriteLine(tag);
                }

                container.AddItem(newItem);

                DatabaseHandler.GetDatabase().AddItem(newItem);

               
            }

        }

        //finishes the container creation
        private async void Finish()
        {

            DataTools.Save(); //save data

            await Navigation.PopAsync(); //go to location page once created

        }

        //compress the picture, move it to the correct directory and renames it
        //returns the new compressed and located image source
        private async Task<ImageSource> ImportPhoto(MediaFile photo)
        {

            ImageBaseHandler.current.AddLocationImage(newItemId, ImageTools.MediaFileToImageSource(photo));
            await ImageTools.ImportImage(photo, Directories.itemImageDirectory, newItemId.ToString());//save the new image in the internal storage with its id as the name
            return ImageTools.MediaFileToImageSource(finalImage);
        }

        //whether or not something can be deleted
        //returns true if any of the tags are highlighted
        public bool CanDelete()
        {
            return tagDisplay.CanDelete();
        }

        //deletes all the highlighted tags
        public void Delete()
        {
            tagDisplay.DeleteTags();
        }

        //has the user scan a barcode and sets the correct text
        public async void ScanBarcode(Object sender, EventArgs args)
        {
            string result = await ExternalResources.ScanBarcode();
            if(result != null)
            {
                codeInput.Text = result;
            }
            
        }


    }
}